version: 0.2

#env:
#  variables:
#    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"
#  parameter-store:
#    LOGIN_PASSWORD: /CodeBuild/dockerLoginPassword

phases:
#  install:
#    commands:
#      - echo Entered the install phase...
#      - apt-get update -y
#      - apt-get install -y maven
#    finally:
#      - echo This always runs even if the update or install command fails
#  pre_build:
#    commands:
#      - echo Entered the pre_build phase...
#      - docker login –u User –p $LOGIN_PASSWORD
#    finally:
#      - echo This always runs even if the login command fails
  build:
    commands:
      - echo Entered the build phase...
      - docker-compose -f local.yml build
      - docker-compose -f local.yml run --rm django python manage.py migrate
      - docker-compose -f local.yml up -d
      - docker-compose -f local.yml exec -T django pytest
  post_build:
    commands:
      - docker-compose -f local.yml down